// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeSxDIHD1bf6vlGmEnKhwo9lpGDWA6450',
    appId: '1:666194711890:web:89e3710a1b6f3c9997968b',
    messagingSenderId: '666194711890',
    projectId: 'asl-app-d2c2c',
    authDomain: 'asl-app-d2c2c.firebaseapp.com',
    storageBucket: 'asl-app-d2c2c.firebasestorage.app',
    measurementId: 'G-X5G7CLJVYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAwmgAj1S8b0McbeSzjy4Wpb00TQUymBQ',
    appId: '1:666194711890:android:d8f116a63cbf159497968b',
    messagingSenderId: '666194711890',
    projectId: 'asl-app-d2c2c',
    storageBucket: 'asl-app-d2c2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZwRYR65ZA6p0X9muTHsNWBn1qXEAqw1c',
    appId: '1:666194711890:ios:864f76c9be3d00c597968b',
    messagingSenderId: '666194711890',
    projectId: 'asl-app-d2c2c',
    storageBucket: 'asl-app-d2c2c.firebasestorage.app',
    iosBundleId: 'com.example.aslApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZwRYR65ZA6p0X9muTHsNWBn1qXEAqw1c',
    appId: '1:666194711890:ios:864f76c9be3d00c597968b',
    messagingSenderId: '666194711890',
    projectId: 'asl-app-d2c2c',
    storageBucket: 'asl-app-d2c2c.firebasestorage.app',
    iosBundleId: 'com.example.aslApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeSxDIHD1bf6vlGmEnKhwo9lpGDWA6450',
    appId: '1:666194711890:web:57d9ab0ed731ec0c97968b',
    messagingSenderId: '666194711890',
    projectId: 'asl-app-d2c2c',
    authDomain: 'asl-app-d2c2c.firebaseapp.com',
    storageBucket: 'asl-app-d2c2c.firebasestorage.app',
    measurementId: 'G-YRLD43QD6X',
  );
}
